### ISSUE TITLE
AttributeError: 'SpecifierSet' object has no attribute 'split'

### ISSUE THREAD

**Issue by gdot709** [kaitai-io/kaitai_struct_python_runtime#47] opened 2020-04-29 21:05 UTC
I'm unable to install this via pip since commit b18ba4f4ab0c87d5cc04009451d0968beba31f0e
```bash
# pip install --upgrade --pre git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git@b18ba4f4ab0c87d5cc04009451d0968beba31f0e
Collecting git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git@b18ba4f4ab0c87d5cc04009451d0968beba31f0e
  Cloning https://github.com/kaitai-io/kaitai_struct_python_runtime.git (to revision b18ba4f4ab0c87d5cc04009451d0968beba31f0e) to /tmp/pip-req-build-4kvsrrc6
  Running command git clone -q https://github.com/kaitai-io/kaitai_struct_python_runtime.git /tmp/pip-req-build-4kvsrrc6
  Running command git checkout -q b18ba4f4ab0c87d5cc04009451d0968beba31f0e
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4kvsrrc6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4kvsrrc6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gi747nqb
         cwd: /tmp/pip-req-build-4kvsrrc6/
    Complete output (21 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4kvsrrc6/setup.py", line 10, in <module>
        setup(**cfg)
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 425, in __init__
        _Distribution.__init__(self, {
      File "/usr/local/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 717, in finalize_options
        ep(self)
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 724, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 289, in check_specifier
        packaging.specifiers.SpecifierSet(value)
      File "/usr/local/lib/python3.8/site-packages/setuptools/_vendor/packaging/specifiers.py", line 572, in __init__
        specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
    AttributeError: 'SpecifierSet' object has no attribute 'split'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems related to https://github.com/pypa/setuptools/issues/1869

**Comment by generalmimon** [comment] 2020-04-29 21:37
Closing as duplicate of https://github.com/kaitai-io/kaitai_struct_python_runtime/issues/45.

@gdot709 Please do some search next time if the problem you want to report isn't covered by an existing issue before opening a new one. It's funny that you named the issue exactly the same as https://github.com/kaitai-io/kaitai_struct_python_runtime/issues/45. But GitHub usually warns about similar issues when opening a new one, it's strange that you didn't notice it.

**Closed by generalmimon** 2020-04-29 21:37 UTC
Labels: duplicate
