### ISSUE TITLE
Issue while installing with setuptools==46 

### ISSUE THREAD

**Issue by H4rryK4ne** [kaitai-io/kaitai_struct_python_runtime#43] opened 2020-03-18 08:19 UTC
Hi guys,

when I tried to install kaitaistruct for python I got this error message:
```
E:\Documents\SourceCode\vwgroup\EthernetTraceAnalysis\ethernet_evaluation_meb>pip install --upgrade --pre git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git
Collecting git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git
  Cloning https://github.com/kaitai-io/kaitai_struct_python_runtime.git to c:\users\harryk~1\appdata\local\temp\pip-req-build-uaees51r
  Running command git clone -q https://github.com/kaitai-io/kaitai_struct_python_runtime.git 'C:\Users\HARRYK~1\AppData\Local\Temp\pip-req-build-uaees51r'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\harrykane\appdata\local\programs\python\python35\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HARRYK~1\\AppData\\Local\\Temp\\pip-req-build-uaees51r\\setup.py'"'"'; __file__='"'"'C:\\Users\\HARRYK~1\\AppData\\Local\\Temp\\pip-req-build-uaees51r\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HARRYK~1\AppData\Local\Temp\pip-req-build-uaees51r\pip-egg-info'
         cwd: C:\Users\HARRYK~1\AppData\Local\Temp\pip-req-build-uaees51r\
    Complete output (21 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HARRYK~1\AppData\Local\Temp\pip-req-build-uaees51r\setup.py", line 10, in <module>
        setup(**cfg)
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\site-packages\setuptools\dist.py", line 425, in __init__
        k: v for k, v in attrs.items()
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\site-packages\setuptools\dist.py", line 706, in finalize_options
        ep.load()(self)
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\site-packages\setuptools\dist.py", line 713, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\site-packages\setuptools\dist.py", line 288, in check_specifier
        packaging.specifiers.SpecifierSet(value)
      File "c:\users\harrykane\appdata\local\programs\python\python35\lib\site-packages\setuptools\_vendor\packaging\specifiers.py", line 572, in __init__
        specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
    AttributeError: 'SpecifierSet' object has no attribute 'split'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
This disappeared when I downgraded my setuptool version from 46.0.0 to 40.0.0 

Best regards,
Martin

**Comment by GreyCat** [comment] 2020-03-18 11:45
Would https://github.com/kaitai-io/kaitai_struct_python_runtime/pull/39 bring a solution to this problem?

**Comment by dgelessus** [comment] 2020-03-18 13:21
This error is caused by setup.py files trying to read setup.cfg manually, which is not officially supported (see pypa/setuptools#1869). You're supposed to just call `setup()` without arguments and let setuptools find and read the setup.cfg file itself.

Yes, this would be fixed by #39, but I personally still think that the PR is not acceptable in its current state - see my review comments on the PR, specifically the ones about Python 2 compatibility.

**Comment by Barracuda72** [comment] 2020-04-06 19:42
Fails on setuptools==44.0.0 also.

**Comment by Barracuda72** [comment] 2020-04-07 13:42
... and I can't downgrade to setuptools <44.0.0 because there's none in Gentoo.
Also can't downgrade Kaitai runtime version to 0.8.0 as I have to use devel IDE cause of https://github.com/kaitai-io/kaitai_struct_webide/issues/68 . Sweet.

Tried #39, works for me. But I don't care about Py2.

**Closed** 2020-04-30 11:32 UTC
